env:
  # $TERM変数を'xterm-256colorに設定'
  TERM: xterm-256color

window:
  # 起動時ウィンドウサイズ
  startup_mode: Maximized 
  # 透過率
  # version > 0.9.0
  opacity: 0.8

# 透過率
# version <= 0.9.0
#background_opacity: 0.75

#font:
#  normal:
#    family: "BitstreamVeraSansMono Nerd Font" 
#  bold:
#    family: "BitstreamVeraSansMono Nerd Font"
#  italic:
#    family: "BitstreamVeraSansMono Nerd Font"
#  bold_italic:
#    family: "BitstreamVeraSansMono Nerd Font"
#  size: 15

# フォント設定はローカル設定を使う
import:
  - ~/alacritty-font.yml

# 背景色透過
# version > 0.9.0
colors:
 transparent_background_colors: true
