[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'haishanh/night-owl.vim'
hook_add = '''
  colorscheme night-owl
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \   'active': {
  \     'left': [ 
  \               [ 'mode', 'paste' ],
  \               [ 'gitbranch', 'readonly', 'filename', 'modified' ] 
  \             ]
  \   },
  \   'component_function': {
  \    'gitbranch': 'gitbranch#name'
  \   },
  \ }
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  nnoremap <silent> <leader>nt :Fern . -drawer -reveal=% -toggle<CR>
  nnoremap <silent> <leader>nr :call <SID>fern_do_reveal_current()<CR>
  let g:fern#default_hidden=1
  augroup fern
    autocmd!
    autocmd FileType fern nmap <buffer> r <Plug>(fern-action-remove)
  augroup END
  function! s:cd_with_fern_open(path)
    execute 'cd ' . a:path
    execute 'Fern . -reveal=%'
  endfunction
  command! -complete=file -nargs=1 Cdf :call s:cd_with_fern_open(<q-args>)
  function! s:fern_do_reveal_current() abort
    let current_path = expand('%:.')
    execute 'FernDo ' . 'FernReveal ' . current_path
  endfunction
'''

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'junegunn/fzf'
merged = 0
hook_add = '''
  let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.85 } }
  if executable('fd')
    let $FZF_DEFAULT_COMMAND = 'fd --strip-cwd-prefix --type f -H --exclude ".git/"'
  endif
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
  let g:fzf_preview_window = ['up:45%', 'ctrl-/']
  nnoremap <silent> <leader>f :Files<CR>
  nnoremap <silent> <leader>gf :GFiles<CR>
  nnoremap <silent> <leader>s :GFiles?<CR>
  nnoremap <silent> <leader>b :Buffers<CR>
  function! s:fzf_with_ghq() abort
    if !executable('ghq')
      echoerr "ghq is not installed."
      return
    endif
    call fzf#run(fzf#wrap({'source': 'ghq list --full-path', 'sink': function('s:cd_with_fern_open') }))
  endfunction
  nnoremap <silent> <leader>nf :call <SID>fzf_with_ghq()<CR>
'''
