[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  nmap <silent> gd <Plug>(lsp-definition)
  nmap <silent> gy <Plug>(lsp-type-definition)
  nmap <silent> gi <Plug>(lsp-implementation)
  nmap <silent> gr <Plug>(lsp-references)
  nmap <silent> gn <Plug>(lsp-rename)
  function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    else
      execute 'LspHover'
    endif
  endfunction
  augroup lsp_installed
    au!
    autocmd User lsp_buffer_enabled nnoremap <silent> K :call <SID>show_documentation()<CR>
  augroup END
  augroup auto_organize
    au!
    autocmd BufWritePre *.go,*.java LspDocumentFormatSync
  augroup END
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
