[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
  inoremap <silent><expr> <TAB>
  \ ddc#map#pum_visible() ? '<C-n>' :
  \ (col('.') <= 1 
  \   <Bar><Bar> getline('.')[col('.') - 2] =~# '\s'
  \   <Bar><Bar> getline('.')[col('.') - 2] =~# '\\') ? '<TAB>' : 
  \ ddc#map#manual_complete()
  inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'
  call ddc#custom#patch_global('sources', ['vim-lsp', 'around', 'file'])
  call ddc#custom#patch_global('sourceOptions', {
        \   '_' : {
        \      'matchers' : ['matcher_head'],
        \      'sorters'  : ['sorter_rank'],
        \   },
        \   'vim-lsp' : {
        \     'mark' : '[lsp]',
        \     'isVolatile' : v:true,
        \     'forceCompletionPattern': '\.',
        \   },
        \   'around'  : {'mark' : '[A]'},
        \   'file'    : {
        \     'mark' : '[file]',
        \     'isVolatile' : v:true,
        \     'forceCompletionPattern' : '\S/\S*'
        \   },
        \ })
  call ddc#enable()
'''

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'LumaKernel/ddc-file'
