[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
  inoremap <silent><expr> <TAB>
  \ ddc#map#pum_visible() ? '<C-n>' :
  \ (col('.') <= 1 
  \   <Bar><Bar> getline('.')[col('.') - 2] =~# '\s'
  \   <Bar><Bar> getline('.')[col('.') - 2] =~# '\\') ? '<TAB>' : 
  \ ddc#map#manual_complete()
  inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'
  " call ddc#custom#patch_global('sources', ['vim-lsp', 'around', 'file'])
  call ddc#custom#patch_global('sources', ['nvim-lsp', 'around', 'file'])
  call ddc#custom#patch_global('sourceOptions', {
        \   '_' : {
        \      'matchers' : ['matcher_head'],
        \      'sorters'  : ['sorter_rank'],
        \   },
        \   'around'  : {'mark' : '[A]'},
        \   'file'    : {
        \     'mark' : '[file]',
        \     'isVolatile' : v:true,
        \     'forceCompletionPattern' : '\S/\S*'
        \   },
        \ })
	if !has('nvim')
		call ddc#custom#patch_global('sourceOptions', {
					\   'vim-lsp' : {
					\     'mark' : '[lsp]',
					\     'isVolatile' : v:true,
					\     'forceCompletionPattern': '\.',
					\   },
		\ })
	else
		call ddc#custom#patch_global('sourceOptions', {
					\   'nvim-lsp' : {
					\     'mark' : '[lsp]',
					\     'isVolatile' : v:true,
					\     'forceCompletionPattern': '\.',
					\   },
					\ })
	endif
	call ddc#enable()
'''
depends = ['denops.vim']

[[plugins]]
repo = 'shun/ddc-vim-lsp'
if = '!has("nvim")'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
if = 'has("nvim")'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-around'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-file'
depends = ['ddc.vim']
