[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
lua << EOF
local on_attach = function(client, bufnr)
	local bufopts = { noremap=true, silent=true, buffer=bufnr }
	vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
	vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
	vim.keymap.set('n', 'gn', vim.lsp.buf.rename, bufopts)
	vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
	vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
end
local lsp_installer = require "nvim-lsp-installer"
local lspconfig = require "lspconfig"
lsp_installer.setup()
for _, server in ipairs(lsp_installer.get_installed_servers()) do
	lspconfig[server.name].setup {
		on_attach = on_attach,
	}
end
EOF
set completeopt-=preview
'''

[[plugins]]
repo = 'mfussenegger/nvim-jdtls'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_add = '''
call popup_preview#enable()
'''
