[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = ['Gina*']
hook_add = '''
  nnoremap <silent> <leader>ts :Gina status<CR>
  nnoremap <silent> <leader>td :Gina diff<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['java', 'go']
hook_add = '''
  let g:vimspector_enable_mappings = "HUMAN"
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = ['markdown']
on_cmd = ['PreviewMarkdown*']
hook_add = '''
  nnoremap <silent> <leader>ma :PreviewMarkdown right<CR>
  let g:preview_markdown_parser = "glow"
  let g:preview_markdown_auto_update = 1
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
on_path = '.*'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_path = '.*\.csv'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'vim-test/vim-test'
depends = ['vim-dispatch']
on_cmd = ['Test*']
hook_add = '''
  let g:test#strategy = 'dispatch'
  nnoremap <silent> <leader>tf :TestFile<CR>
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
  let g:goimports = 1
'''
