[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_source = '''
lua << EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {"help",},
  },
}
EOF
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = '''
  syntax enable
  colorscheme Dayfox
'''

[[plugins]]
repo = 'nanozuki/tabby.nvim'
hook_add = '''
lua << EOF
require"tabby".setup()
EOF
'''

[[plugins]]
repo = 'feline-nvim/feline.nvim'
hook_add = '''
lua << EOF
require('feline').setup()
EOF
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
